---
title: "Threatened Australians: A model for catalysing conservation knowledge and action through a digital platform"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
bibliography: /home/gareth/science/admin/bibliography/zotero_lib_exports/sees_pop_os_my_library.bib
biblio-style: apsr
link-citations: yes
csl: /home/gareth/science/admin/bibliography/csls/apa.csl
output:
  word_document:
    reference_docx: /home/gareth/science/admin/bibliography/word_templates/research_article_template.docx
editor_options:
  markdown:
    wrap: 72
---

## Authors

Gareth S. Kindler^1,^\*, Nick Kelly^2^, James E.M. Watson^2^ [social
scientist? (they get mad about not being included from the beginning),
digital tech/advertising/GA4 wiz?, ]

## Affiliations

1.  School of Earth and Environmental Sciences, The University of
    Queensland, St Lucia 4072, Australia
2.  [Add your affil here please Nick] School, Queensland University of
    Technology, suburb, postcode, Australia

\***Corresponding author email**:
[g.kindler\@uq.edu.au](mailto:g.kindler@uq.edu.au){.email}

**Keywords**: threatened species, digital technology, conservation
science, design

Target journals: Any of conservation journal (?), Journal of
Environmental Media
(<https://www.intellectbooks.com/journal-of-environmental-media>)

\newpage

<!-- ## Model papers -->

<!-- The papers I have found are about exploratory/educational/interactive -->

<!-- tools that visualise some aspect of the author's work. That's not -->

<!-- completely dissimilar to TA but it's not quite where we are at. I guess -->

<!-- people/orgs who develop advocacy web apps like TA don't write about it -->

<!-- in journals? -->

<!-- -   VolcanNoseR - <https://doi.org/10.1038/s41598-020-76603-3> -->

<!-- -   SpeciesMap - <https://doi.org/10.1007/s10531-012-0284-4> -->

<!-- -   BioDem - <https://doi.org/10.1111/jbi.14256> -->

<!-- -   Pop viability - <https://doi.org/10.1111/nrm.12120> -->

<!-- -   Niggle - <https://doi.org/10.2196/21085> -->

# Draft

## Abstract

Government action for species conservation is dependent upon public
support. Whilst scientists, NGOs, and government have developed tools
that improve accessibility, they fall short of engaging the broader
public. Here we discuss the Threatened Australians web app, which uses
existing data to tell the story of threatened species occurrence within
government constituency boundaries, as an attempt to facilitate public
support and thus political action. By examining the development, launch,
and maintenance, this helps inform/improve future efforts the
conservation community make in engaging broader audiences.

## Introduction

### Para 1 - Biodiversity crisis in Australia

Keys refs: Kearney, Ward, State of Environments etc

Summarise threatened species and ecosystems. The rates of species
endangerment and ecosystem decay is on the increase.

### Para 2 - Conservation crisis in Australia

Key papers: @whitelawBiodiversityDataPublic2021,

On top of a biodiversity crisis, there is a conservation crisis in
Australia. There conservation crisis is a lack of conservation attention
focussed at the biodiversity crisis. Key references National Audits,
Samuel reviews, review and perspective papers by scientists (Reside etc)
all show there is a lack of resources and action by leaders. Moreover,
and related, there are clear shortfalls in Australians knowing or
engaging with the issue. There is a clear need for new models in
conservation to catalyse change.

### Para 3 - Digital technology as an intervention for action

Much hype around social media and apps to increase attention on social
issues. Climate example, health examples? Yet in conservation, despite
being a crisis discipline needing advocates, and wider society buy-in,
there seems bereft of these social media initiatives connecting people
to the problem. Most social media efforts in conservation and ecology
has been focussed on the needs of the science (key refs include the
papers already sent, we will need others) rather than disseminating the
finding to the audience to the general public to advocate for change.

### Para 4 - Objective/aims

Here we provide a description of one of the first proactive attempts by
a multidisciplinary team to provide a web app aimed at raising public
attention around the species conservation crisis in Australia. Called
"Threatened Australians", its aim is to raise awareness of the plight of
threatened species, specifically there locations and threats. It was
linked to post code so to bring get local attention (Refs on need for
local action) and timed before the 2022 federal election so as to bring
attention specifically around federal politicians. Therefore the key
spatial boundaries used were federal electorates. We describe the
generation of the prototype and testing methods, public usage of the app
once realised and how this varied across different electorates.

## Methods

Key papers: @hendrieImpactMobilePhone2020,

### Para 1 - App design

We first created a prototype by doing XXXXX.

We then ran it by experts in five of Australia's largest conservation
NGOs groups via XX feedback sessions and then re-designed it and did
another run. (This needs to be filled out). Via this process it was
decided the app interface would cover the following aspects (summarise
the app).

Threatened Australians as a web app available at a web domain
(threatened.org.au) through browser applications on mobile, desktop, and
tablet.

The primary outcome of the web app was communicating with elected
representatives.

We aggregated data from X sources.

**Figure 1. an image of the front cover off the app showcasing its
features OR images of key pages and how users are to move through them
[@hendrieImpactMobilePhone2020]**

### Para 2 - App deployment and media

Accompanying the live version of the app was a media release, which was
sent out to Australian local and international media outlets.
Accompanying the release date (02/05/22) was a 'The Conversation"
article and efforts were made via social media to promote the web app.

When released, a media release was sent out as was a conversation piece
and efforts were made via different mechanisms to raise attention via
social media (explain what was done).

Dom's media report here?

### Para 3 - Data collection

We generated the data via XXX (describe this in detail)

Two data sources:

Analytics:

Data on website usage was collected via Google Analytics 4.

Feedback:

There were free-text questions but these provided misc results. We
filtered these out and went with: Q: "Are you going to take any actions
as a result of using the web app?"; Q: "The information on this website
was easy to understand:".

### Para 4 - Data processing and analysis

How app usage data was extracted.

Descriptive statistics of usage etc were used to...

## Results

Research questions

-   How did our traffic acquisition change over time, drawn next to key
    media events?

-   How did

### Para 1 - Description of users and timing

Released XXX. #% of users prior to election day. Over the course of X
days up to federal election, \# Number of people and hits over time
(Figure 2). Over the

**Figure 2. a time series of usage, including key media events**

### Para 2 - How patterns differentiate

Number of electorates and density of hits across space. Describe
patterns

**Figure 3. A map of Australia with hits.**

Number of species investigated and most popular species were XXX.

**Figure 4. a map of the locations of the top 5-10 species and how many
hits they had, and a photo of each of them**

**Figure 5. Sankey of movement throughout platform**

## Discussion

### Para 1 - Summary

We provide the first app that attempts to put species and threat
information on Australia's threatened species into the hands of the
public. In the space of a month, -- users, across all federal
electorates engage with it showing there was widespread interest. There
was also media interest, with ABC online story and over 30 radio
interviews conducted on local stories around the country. The appetite
seemed there.

### Para 2 - How to do it more robustly

This is a first attempt and done via just two rounds of review by NGOS.
A more systematic way of doing this would be Y, X, and Z (use the theory
in the paper that was shared to describe how to more robustly do it but
also need to refer to other non biodiversity literature about what is
working and what we could do better. ).

### Para 3 - Further customisation/targeting is needed

Further work is needed to catalyse not just linking the threat to place,
but the actual actions needed to be activated in the place. This type of
connection between people and actions is likely critical pathway to
action.

Constantly evolving socio-political context

### Para 4 - Education opportunities

There is also significant opportunities with the education dynamics and
children. Children in schools increasingly use social media as part of
their learning packages (refs) and a app that links education to
awareness and advocacy is clearly missing.

### Para 5 - Conclusion

Our efforts are a first attempt to get over a gap in the conservation
space around making people aware of the challenges biodiversity faces
and what they can do about it. It takes advantage of significant gains
in science over the past decade documenting ranges and threats to
species (cite NESP 7.7) and tries to generate information in a
accessible to the general public. More is needed to get action etc and
we have attempted to provide one model to bridge the knowledge-advocacy
gap.

### Para X - Caveats

-   Didn't organise anything prior to app release (lol)

## Supporting information

## Acknowledgements

The authors would like to recognise...  

The authors declare no conflicts of interest. 

## Data

All data used to produce the Threatened Australians database is
available on GitHub.

Raw, clean, and analysed data produced by Threatened Australians is
available on UQ eSpace
